export const FETCH_LOTS = 'FETCH_LOTS';
export const FETCH_LOTS_SUCCESS = 'FETCH_LOTS_SUCCESS';
export const FETCH_LOTS_FAIL = 'FETCH_LOTS_FAIL';

export const FETCH_SETTINGS = 'FETCH_SETTINGS';
export const FETCH_SETTINGS_SUCCESS = 'FETCH_SETTINGS_SUCCESS';
export const FETCH_SETTINGS_FAIL = 'FETCH_SETTINGS_FAIL';
