version: '3.5'

services:

  expo:
    container_name: expo
    image: usedcar-test
    build:
      context: .
      dockerfile: docker/mobilebuilder/Dockerfile
      args:
        - EXPO_USER=${EXPO_USER}
        - EXPO_PASSWORD=${EXPO_PASSWORD}
    env_file: .env
    volumes:
      - ./src:/usr/src/app/src
    ports:
     - 19000:19000
     - 19001:19001
     - 19002:19002
