export const FETCH_CAR_LOTS = 'FETCH_CAR_LOTS';
export const FETCH_CAR_LOTS_SUCCESS = 'FETCH_CAR_LOTS_SUCCESS';
export const FETCH_CAR_LOTS_FAIL = 'FETCH_CAR_LOTS_FAIL';

export const FETCH_HOUSE_LOTS = 'FETCH_HOUSE_LOTS';
export const FETCH_HOUSE_LOTS_SUCCESS = 'FETCH_HOUSE_LOTS_SUCCESS';
export const FETCH_HOUSE_LOTS_FAIL = 'FETCH_HOUSE_LOTS_FAIL';

export const FETCH_SETTINGS = 'FETCH_SETTINGS';
export const FETCH_SETTINGS_SUCCESS = 'FETCH_SETTINGS_SUCCESS';
export const FETCH_SETTINGS_FAIL = 'FETCH_SETTINGS_FAIL';
export const CHANGE_SETTING = 'CHANGE_SETTING';

export const UPDATE_HOUSE_WATCH_LOTS = 'UPDATE_HOUSE_WATCH_LOTS';
export const UPDATE_HOUSE_WATCH_LOTS_SUCCESS = 'UPDATE_HOUSE_WATCH_LOTS_SUCCESS';
export const UPDATE_HOUSE_WATCH_LOTS_FAIL = 'UPDATE_HOUSE_WATCH_LOTS_FAIL';

export const FETCH_AUTH_KEY = 'FETCH_AUTH_KEY';
export const FETCH_AUTH_KEY_SUCCESS = 'FETCH_AUTH_KEY_SUCCESS';
export const FETCH_AUTH_KEY_FAIL = 'FETCH_AUTH_KEY_FAIL';