export const APP_READY = 'APP_READY';

export const NAVIGATE = 'NAVIGATE';
export const NAVIGATE_DEEP = 'NAVIGATE_DEEP';
export const RESET = 'RESET';

export const FETCH_CAR_LOTS = 'FETCH_CAR_LOTS';
export const FETCH_CAR_LOTS_SUCCESS = 'FETCH_CAR_LOTS_SUCCESS';
export const FETCH_CAR_LOTS_FAIL = 'FETCH_CAR_LOTS_FAIL';

export const FETCH_HOUSE_LOTS = 'FETCH_HOUSE_LOTS';
export const FETCH_HOUSE_LOTS_SUCCESS = 'FETCH_HOUSE_LOTS_SUCCESS';
export const FETCH_HOUSE_LOTS_FAIL = 'FETCH_HOUSE_LOTS_FAIL';

export const UPDATE_HOUSE_FILTER_ROOMS_TO = 'UPDATE_HOUSE_FILTER_ROOMS_TO';
export const UPDATE_HOUSE_FILTER_ROOMS_FROM = 'UPDATE_HOUSE_FILTER_ROOMS_FROM';
export const UPDATE_HOUSE_FILTER_PRICE_TO = 'UPDATE_HOUSE_FILTER_PRICE_TO';
export const UPDATE_HOUSE_FILTER_PRICE_FROM = 'UPDATE_HOUSE_FILTER_PRICE_FROM';

export const UPDATE_HOUSE_WATCH_FILTER_ROOMS_TO = 'UPDATE_HOUSE_WATCH_FILTER_ROOMS_TO';
export const UPDATE_HOUSE_WATCH_FILTER_ROOMS_FROM = 'UPDATE_HOUSE_WATCH_FILTER_ROOMS_FROM';
export const UPDATE_HOUSE_WATCH_FILTER_PRICE_TO = 'UPDATE_HOUSE_WATCH_FILTER_PRICE_TO';
export const UPDATE_HOUSE_WATCH_FILTER_PRICE_FROM = 'UPDATE_HOUSE_WATCH_FILTER_PRICE_FROM';

export const UPDATE_WATCH_STATE = 'UPDATE_WATCH_STATE';

export const FETCH_SETTINGS = 'FETCH_SETTINGS';
export const FETCH_SETTINGS_SUCCESS = 'FETCH_SETTINGS_SUCCESS';
export const FETCH_SETTINGS_FAIL = 'FETCH_SETTINGS_FAIL';
export const CHANGE_SETTING = 'CHANGE_SETTING';

export const UPDATE_HOUSE_WATCH_LOTS = 'UPDATE_HOUSE_WATCH_LOTS';
export const UPDATE_HOUSE_WATCH_LOTS_SUCCESS = 'UPDATE_HOUSE_WATCH_LOTS_SUCCESS';
export const UPDATE_HOUSE_WATCH_LOTS_FAIL = 'UPDATE_HOUSE_WATCH_LOTS_FAIL';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const CHECK_IF_LOGGED_IN = 'CHECK_IF_LOGGED_IN';
export const SHOW_FIRST_SPLASH_SCREEN = 'SHOW_FIRST_SPLASH_SCREEN';
