export const APP_READY = 'APP_READY';

export const NAVIGATE = 'NAVIGATE';
export const NAVIGATE_DEEP = 'NAVIGATE_DEEP';
export const RESET = 'RESET';

export const FETCH_CAR_LOTS = 'FETCH_CAR_LOTS';
export const FETCH_CAR_LOTS_SUCCESS = 'FETCH_CAR_LOTS_SUCCESS';
export const FETCH_CAR_LOTS_FAIL = 'FETCH_CAR_LOTS_FAIL';

export const FETCH_HOUSE_LOTS = 'FETCH_HOUSE_LOTS';
export const FETCH_HOUSE_LOTS_SUCCESS = 'FETCH_HOUSE_LOTS_SUCCESS';
export const FETCH_HOUSE_LOTS_FAIL = 'FETCH_HOUSE_LOTS_FAIL';

export const UPDATE_HOUSE_FILTER_PRICE_TO = 'UPDATE_HOUSE_FILTER_PRICE_TO';
export const UPDATE_HOUSE_FILTER_PRICE_FROM = 'UPDATE_HOUSE_FILTER_PRICE_FROM';

export const UPDATE_HOUSE_WATCH_FILTER_PRICE_TO = 'UPDATE_HOUSE_WATCH_FILTER_PRICE_TO';
export const UPDATE_HOUSE_WATCH_FILTER_PRICE_FROM = 'UPDATE_HOUSE_WATCH_FILTER_PRICE_FROM';
export const ADD_WATCH_ROOM_COUNT = 'ADD_WATCH_ROOM_COUNT';
export const ADD_ROOM_COUNT = 'ADD_ROOM_COUNT';
export const UPDATE_HOUSE_WATCH_FILTER_APPLY = 'UPDATE_HOUSE_WATCH_FILTER_APPLY';

export const UPDATE_HOUSE_WATCH_STATE = 'UPDATE_HOUSE_WATCH_STATE';
export const FETCH_HOUSE_WATCH_STATE = 'FETCH_HOUSE_WATCH_STATE';
export const FETCH_HOUSE_WATCH_STATE_TRUE = 'FETCH_HOUSE_WATCH_STATE_TRUE';
export const FETCH_HOUSE_WATCH_STATE_FALSE = 'FETCH_HOUSE_WATCH_STATE_FALSE';
export const FETCH_HOUSE_WATCH_STATE_FAIL = 'FETCH_HOUSE_WATCH_STATE_FAIL';

export const UPDATE_HOUSE_WATCH_LOTS = 'UPDATE_HOUSE_WATCH_LOTS';
export const UPDATE_HOUSE_WATCH_LOTS_SUCCESS = 'UPDATE_HOUSE_WATCH_LOTS_SUCCESS';
export const UPDATE_HOUSE_WATCH_LOTS_FAIL = 'UPDATE_HOUSE_WATCH_LOTS_FAIL';

export const REMOVE_HOUSE_WATCH_JOB = 'REMOVE_HOUSE_WATCH_JOB';
export const REMOVE_HOUSE_WATCH_JOB_SUCCESS = 'REMOVE_HOUSE_WATCH_JOB_SUCCESS';
export const REMOVE_HOUSE_WATCH_JOB_FAIL = 'REMOVE_HOUSE_WATCH_JOB_FAIL';

export const PAUSE_HOUSE_WATCH_JOB = 'PAUSE_HOUSE_WATCH_JOB';
export const PAUSE_HOUSE_WATCH_JOB_SUCCESS = 'PAUSE_HOUSE_WATCH_JOB_SUCCESS';
export const PAUSE_HOUSE_WATCH_JOB_FAIL = 'PAUSE_HOUSE_WATCH_JOB_FAIL';

export const RESUME_HOUSE_WATCH_JOB = 'RESUME_HOUSE_WATCH_JOB';
export const EDIT_HOUSE_WATCH_JOB_LIST = 'EDIT_HOUSE_WATCH_JOB_LIST';
export const PAUSED_HOUSE_WATCH_JOBS_TRUE = 'PAUSED_HOUSE_WATCH_JOBS_TRUE';
export const PAUSED_HOUSE_WATCH_JOBS_FALSE = 'PAUSED_HOUSE_WATCH_JOBS_FALSE';
export const CHECK_PAUSED_HOUSE_WATCH_JOBS = 'CHECK_PAUSED_HOUSE_WATCH_JOBS';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const SHOW_FIRST_SPLASH_SCREEN = 'SHOW_FIRST_SPLASH_SCREEN';

export const LOAD_PROFILE = 'LOAD_PROFILE';
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOAD_PROFILE_FAIL = 'LOAD_PROFILE_FAIL';
