export const SETTINGS_SCREEN = 'SETTINGS_SCREEN';
export const CAR_LOTS_SCREEN = 'CAR_LOTS_SCREEN';
export const HOUSE_LOTS_SCREEN = 'HOUSE_LOTS_SCREEN';
export const HOUSE_WATCH_LOTS_SCREEN = 'HOUSE_WATCH_LOTS_SCREEN';
export const AUTH_SIGN_OR_REGISTER_SCREEN = 'AUTH_SIGN_OR_REGISTER_SCREEN';
export const FILTER_SCREEN = 'FILTER_SCREEN';

export const APP_TAB = 'APP_TAB';
export const AUTH_STACK = 'AUTH_STACK';
export const AUTH_LOADING = 'AUTH_LOADING';
